# Generated by Django 3.2.9 on 2021-12-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
        ('products', '0003_auto_20211201_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.perfil'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
